# Generated by Django 4.1.4 on 2023-01-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=500)),
                ('album_name', models.CharField(max_length=500)),
                ('album_logo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
