# Generated by Django 4.1.4 on 2023-01-04 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('file_type', models.FileField(upload_to='mp3')),
                ('song_title', models.CharField(max_length=250)),
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('album_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_library.album')),
            ],
        ),
    ]
