# Generated by Django 4.1.4 on 2023-01-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0002_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_name',
            new_name='alname',
        ),
    ]
