# Generated by Django 4.1.4 on 2023-01-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0003_rename_album_name_song_alname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='alname',
            new_name='album_name',
        ),
    ]
