# Generated by Django 4.1.4 on 2023-01-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0004_rename_alname_song_album_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
