# Generated by Django 4.1.4 on 2023-01-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0009_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='audio_file',
            field=models.FileField(default=0, upload_to='mp3'),
            preserve_default=False,
        ),
    ]
