# Generated by Django 4.1.4 on 2023-01-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0010_playlist_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song_fk',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_id',
            field=models.ManyToManyField(to='music_library.song'),
        ),
    ]
