# Generated by Django 4.1.4 on 2023-01-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0011_remove_playlist_song_fk_playlist_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song_id',
            field=models.ManyToManyField(blank=True, related_name='song_mtm', to='music_library.song'),
        ),
    ]
