# Generated by Django 4.1.4 on 2023-01-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0012_alter_playlist_song_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_pic', models.FileField(upload_to='images')),
            ],
        ),
    ]
