# Generated by Django 4.1.4 on 2023-01-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0013_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music_library.artist'),
            preserve_default=False,
        ),
    ]
