# Generated by Django 4.1.4 on 2023-01-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0014_album_artist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_name',
        ),
    ]
