# Generated by Django 4.1.4 on 2023-01-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0015_remove_album_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_name',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song_id',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music_library.song'),
        ),
    ]
