# Generated by Django 4.1.4 on 2023-01-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0016_remove_song_album_name_alter_playlist_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music_library.album'),
            preserve_default=False,
        ),
    ]
