# Generated by Django 4.1.4 on 2023-01-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0017_song_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='music_library.song'),
            preserve_default=False,
        ),
    ]
