# Generated by Django 4.1.4 on 2023-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0018_remove_playlist_song_id_playlist_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='song_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_id',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='music_library.song'),
        ),
    ]
